[2025-01-28T03:39:49.202+0000] {processor.py:186} INFO - Started process (PID=9646) to work on /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:39:49.203+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T03:39:49.204+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:39:49.204+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:39:49.208+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:39:49.207+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T03:39:49.208+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:39:49.208+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T03:39:49.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:39:49.219+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-01-28T03:40:52.584+0000] {processor.py:186} INFO - Started process (PID=9707) to work on /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:40:52.635+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T03:40:52.638+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:40:52.637+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:40:52.640+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:40:52.640+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T03:40:52.641+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:40:52.640+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T03:40:52.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:40:52.652+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2025-01-28T03:43:29.933+0000] {processor.py:186} INFO - Started process (PID=9808) to work on /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:43:29.936+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T03:43:29.938+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:43:29.937+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:43:29.940+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:43:29.940+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T03:43:29.940+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:43:29.940+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T03:43:29.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:43:29.951+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T03:44:25.721+0000] {processor.py:186} INFO - Started process (PID=9866) to work on /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:44:25.723+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T03:44:25.724+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:44:25.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:44:25.727+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:44:25.727+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T03:44:25.727+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:44:25.727+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T03:44:25.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:44:25.738+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-01-28T03:45:21.619+0000] {processor.py:186} INFO - Started process (PID=9928) to work on /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:45:21.621+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T03:45:21.623+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:45:21.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:45:21.626+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:45:21.625+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T03:45:21.626+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:45:21.626+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T03:45:21.626+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:45:21.637+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T03:46:14.181+0000] {processor.py:186} INFO - Started process (PID=9982) to work on /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:46:14.183+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T03:46:14.185+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:46:14.185+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:46:14.188+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:46:14.187+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T03:46:14.188+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:46:14.188+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T03:46:14.189+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:46:14.199+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T03:47:06.535+0000] {processor.py:186} INFO - Started process (PID=10036) to work on /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:47:06.536+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T03:47:06.538+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:47:06.538+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:47:06.541+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:47:06.541+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T03:47:06.542+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:47:06.542+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T03:47:06.542+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:47:06.552+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T03:47:57.334+0000] {processor.py:186} INFO - Started process (PID=10088) to work on /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:47:57.335+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T03:47:57.338+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:47:57.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:47:57.341+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:47:57.341+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T03:47:57.342+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:47:57.341+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T03:47:57.342+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:47:57.352+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T03:48:49.555+0000] {processor.py:186} INFO - Started process (PID=10143) to work on /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:48:49.557+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T03:48:49.559+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:48:49.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:48:49.562+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:48:49.562+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T03:48:49.563+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:48:49.563+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T03:48:49.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:48:49.572+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-01-28T03:49:39.663+0000] {processor.py:186} INFO - Started process (PID=10195) to work on /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:49:39.665+0000] {processor.py:914} INFO - Processing file /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T03:49:39.667+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:49:39.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:49:39.669+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:49:39.669+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T03:49:39.669+0000] {logging_mixin.py:190} INFO - [2025-01-28T03:49:39.669+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T03:49:39.670+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T03:49:39.680+0000] {processor.py:208} INFO - Processing /home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T05:55:24.898+0000] {processor.py:186} INFO - Started process (PID=1916) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:55:24.900+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T05:55:24.902+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:55:24.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:55:24.906+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:55:24.905+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T05:55:24.906+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:55:24.906+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T05:55:24.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:55:24.916+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T05:56:23.433+0000] {processor.py:186} INFO - Started process (PID=1975) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:56:23.435+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T05:56:23.437+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:56:23.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:56:23.441+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:56:23.440+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T05:56:23.442+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:56:23.442+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T05:56:23.444+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:56:23.458+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-01-28T05:57:20.131+0000] {processor.py:186} INFO - Started process (PID=2067) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:57:20.133+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T05:57:20.135+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:57:20.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:57:20.138+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:57:20.137+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T05:57:20.139+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:57:20.139+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T05:57:20.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:57:20.149+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T05:58:17.970+0000] {processor.py:186} INFO - Started process (PID=2125) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:58:17.972+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T05:58:17.974+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:58:17.974+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:58:17.977+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:58:17.977+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T05:58:17.978+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:58:17.978+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T05:58:17.978+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:58:17.988+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T05:59:13.359+0000] {processor.py:186} INFO - Started process (PID=2182) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:59:13.361+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T05:59:13.363+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:59:13.363+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:59:13.366+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:59:13.365+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T05:59:13.367+0000] {logging_mixin.py:190} INFO - [2025-01-28T05:59:13.367+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T05:59:13.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T05:59:13.378+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:00:07.340+0000] {processor.py:186} INFO - Started process (PID=2238) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:00:07.342+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:00:07.344+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:00:07.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:00:07.348+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:00:07.347+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:00:07.348+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:00:07.348+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:00:07.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:00:07.359+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-01-28T06:00:59.803+0000] {processor.py:186} INFO - Started process (PID=2296) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:00:59.804+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:00:59.806+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:00:59.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:00:59.810+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:00:59.809+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:00:59.810+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:00:59.810+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:00:59.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:00:59.821+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:01:51.564+0000] {processor.py:186} INFO - Started process (PID=2355) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:01:51.567+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:01:51.568+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:01:51.568+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:01:51.572+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:01:51.571+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:01:51.573+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:01:51.572+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:01:51.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:01:51.583+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:02:43.606+0000] {processor.py:186} INFO - Started process (PID=2420) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:02:43.608+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:02:43.610+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:02:43.609+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:02:43.613+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:02:43.612+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:02:43.613+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:02:43.613+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:02:43.613+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:02:43.624+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:03:49.062+0000] {processor.py:186} INFO - Started process (PID=2488) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:03:49.064+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:03:49.066+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:03:49.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:03:49.069+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:03:49.069+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:03:49.070+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:03:49.070+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:03:49.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:03:49.081+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:05:05.582+0000] {processor.py:186} INFO - Started process (PID=2574) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:05:05.583+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:05:05.586+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:05:05.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:05:05.590+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:05:05.589+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:05:05.590+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:05:05.590+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:05:05.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:05:05.601+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-01-28T06:06:11.892+0000] {processor.py:186} INFO - Started process (PID=2649) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:06:11.895+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:06:11.897+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:06:11.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:06:11.900+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:06:11.900+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:06:11.901+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:06:11.901+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:06:11.901+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:06:11.911+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:07:16.484+0000] {processor.py:186} INFO - Started process (PID=2723) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:07:16.485+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:07:16.488+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:07:16.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:07:16.492+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:07:16.492+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:07:16.493+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:07:16.492+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:07:16.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:07:16.503+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:08:14.394+0000] {processor.py:186} INFO - Started process (PID=2781) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:08:14.395+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:08:14.399+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:08:14.398+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:08:14.402+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:08:14.401+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:08:14.402+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:08:14.402+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:08:14.403+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:08:14.412+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:09:11.049+0000] {processor.py:186} INFO - Started process (PID=2840) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:09:11.051+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:09:11.053+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:09:11.053+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:09:11.057+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:09:11.056+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:09:11.058+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:09:11.058+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:09:11.058+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:09:11.068+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:10:03.469+0000] {processor.py:186} INFO - Started process (PID=2910) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:10:03.472+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:10:03.474+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:10:03.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:10:03.478+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:10:03.477+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:10:03.478+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:10:03.478+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:10:03.478+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:10:03.489+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:10:57.682+0000] {processor.py:186} INFO - Started process (PID=2974) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:10:57.684+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:10:57.686+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:10:57.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:10:57.690+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:10:57.689+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:10:57.690+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:10:57.690+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:10:57.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:10:57.700+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:11:50.446+0000] {processor.py:186} INFO - Started process (PID=3031) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:11:50.448+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:11:50.450+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:11:50.450+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:11:50.454+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:11:50.454+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:11:50.454+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:11:50.454+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:11:50.455+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:11:50.465+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-01-28T06:12:44.789+0000] {processor.py:186} INFO - Started process (PID=3085) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:12:44.791+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:12:44.795+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:12:44.794+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:12:44.800+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:12:44.799+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:12:44.802+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:12:44.802+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:12:44.802+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:12:44.812+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-01-28T06:13:39.012+0000] {processor.py:186} INFO - Started process (PID=3142) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:13:39.014+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:13:39.019+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:13:39.018+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:13:39.025+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:13:39.024+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:13:39.025+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:13:39.025+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:13:39.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:13:39.036+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-01-28T06:14:31.251+0000] {processor.py:186} INFO - Started process (PID=3197) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:14:31.252+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:14:31.255+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:14:31.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:14:31.259+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:14:31.258+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:14:31.259+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:14:31.259+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:14:31.259+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:14:31.270+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:15:24.930+0000] {processor.py:186} INFO - Started process (PID=3256) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:15:24.934+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:15:24.935+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:15:24.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:15:24.939+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:15:24.939+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:15:24.940+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:15:24.940+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:15:24.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:15:24.950+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-01-28T06:16:16.653+0000] {processor.py:186} INFO - Started process (PID=3310) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:16:16.655+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:16:16.657+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:16:16.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:16:16.661+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:16:16.660+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:16:16.661+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:16:16.661+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:16:16.662+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:16:16.671+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:17:10.663+0000] {processor.py:186} INFO - Started process (PID=3369) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:17:10.665+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:17:10.668+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:17:10.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:17:10.672+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:17:10.670+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:17:10.672+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:17:10.672+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:17:10.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:17:10.682+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:18:17.502+0000] {processor.py:186} INFO - Started process (PID=3479) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:18:17.503+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:18:17.506+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:18:17.506+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:18:17.509+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:18:17.509+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:18:17.510+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:18:17.510+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:18:17.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:18:17.520+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:19:12.203+0000] {processor.py:186} INFO - Started process (PID=3537) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:19:12.205+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:19:12.207+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:19:12.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:19:12.211+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:19:12.210+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:19:12.211+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:19:12.211+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:19:12.211+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:19:12.222+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:20:05.171+0000] {processor.py:186} INFO - Started process (PID=3594) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:20:05.172+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:20:05.175+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:20:05.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:20:05.179+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:20:05.178+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:20:05.179+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:20:05.179+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:20:05.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:20:05.191+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-01-28T06:21:01.478+0000] {processor.py:186} INFO - Started process (PID=3733) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:21:01.481+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:21:01.483+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:21:01.483+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:21:01.486+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:21:01.486+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:21:01.486+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:21:01.486+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:21:01.487+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:21:01.497+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:21:54.447+0000] {processor.py:186} INFO - Started process (PID=3851) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:21:54.449+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:21:54.451+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:21:54.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:21:54.457+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:21:54.456+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:21:54.457+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:21:54.457+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:21:54.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:21:54.468+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-01-28T06:22:54.813+0000] {processor.py:186} INFO - Started process (PID=3917) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:22:54.815+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:22:54.818+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:22:54.818+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:22:54.822+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:22:54.821+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:22:54.822+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:22:54.822+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:22:54.822+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:22:54.832+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-01-28T06:23:48.557+0000] {processor.py:186} INFO - Started process (PID=4440) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:23:48.559+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:23:48.561+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:23:48.560+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:23:48.565+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:23:48.565+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:23:48.565+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:23:48.565+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:23:48.566+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:23:48.577+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-01-28T06:24:43.485+0000] {processor.py:186} INFO - Started process (PID=4564) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:24:43.486+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:24:43.488+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:24:43.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:24:43.492+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:24:43.491+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:24:43.492+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:24:43.492+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:24:43.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:24:43.502+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:25:37.472+0000] {processor.py:186} INFO - Started process (PID=5018) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:25:37.474+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:25:37.476+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:25:37.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:25:37.480+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:25:37.479+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:25:37.480+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:25:37.480+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:25:37.480+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:25:37.490+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:26:31.433+0000] {processor.py:186} INFO - Started process (PID=5169) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:26:31.434+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:26:31.437+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:26:31.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:26:31.440+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:26:31.440+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:26:31.441+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:26:31.441+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:26:31.441+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:26:31.451+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:27:24.913+0000] {processor.py:186} INFO - Started process (PID=5225) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:27:24.915+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:27:24.918+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:27:24.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:27:24.922+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:27:24.921+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:27:24.922+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:27:24.922+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:27:24.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:27:24.932+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:28:16.381+0000] {processor.py:186} INFO - Started process (PID=5305) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:28:16.383+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:28:16.385+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:28:16.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:28:16.388+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:28:16.388+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:28:16.389+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:28:16.389+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:28:16.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:28:16.400+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:29:11.284+0000] {processor.py:186} INFO - Started process (PID=5554) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:29:11.286+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:29:11.288+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:29:11.288+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:29:11.291+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:29:11.290+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:29:11.292+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:29:11.291+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:29:11.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:29:11.302+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:30:06.492+0000] {processor.py:186} INFO - Started process (PID=5612) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:30:06.493+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:30:06.496+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:30:06.496+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:30:06.500+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:30:06.499+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:30:06.500+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:30:06.500+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:30:06.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:30:06.510+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:31:00.635+0000] {processor.py:186} INFO - Started process (PID=5720) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:31:00.637+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:31:00.639+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:31:00.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:31:00.643+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:31:00.642+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:31:00.643+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:31:00.643+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:31:00.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:31:00.654+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-01-28T06:32:23.584+0000] {processor.py:186} INFO - Started process (PID=5804) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:32:23.586+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:32:23.589+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:32:23.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:32:23.592+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:32:23.591+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:32:23.592+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:32:23.592+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:32:23.592+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:32:23.603+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-01-28T06:33:18.108+0000] {processor.py:186} INFO - Started process (PID=5863) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:33:18.110+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:33:18.112+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:33:18.111+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:33:18.114+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:33:18.114+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:33:18.115+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:33:18.115+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:33:18.116+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:33:18.125+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:34:18.822+0000] {processor.py:186} INFO - Started process (PID=5926) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:34:18.823+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:34:18.826+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:34:18.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:34:18.830+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:34:18.829+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:34:18.830+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:34:18.830+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:34:18.830+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:34:18.841+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:35:14.401+0000] {processor.py:186} INFO - Started process (PID=5986) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:35:14.403+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:35:14.406+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:35:14.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:35:14.409+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:35:14.408+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:35:14.409+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:35:14.409+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:35:14.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:35:14.420+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-01-28T06:36:08.217+0000] {processor.py:186} INFO - Started process (PID=6042) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:36:08.219+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:36:08.221+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:36:08.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:36:08.225+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:36:08.224+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:36:08.225+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:36:08.225+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:36:08.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:36:08.236+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:36:59.144+0000] {processor.py:186} INFO - Started process (PID=6095) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:36:59.145+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:36:59.148+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:36:59.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:36:59.151+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:36:59.150+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:36:59.152+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:36:59.152+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:36:59.152+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:36:59.162+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:37:52.370+0000] {processor.py:186} INFO - Started process (PID=6150) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:37:52.371+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:37:52.373+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:37:52.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:37:52.376+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:37:52.375+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:37:52.377+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:37:52.377+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:37:52.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:37:52.387+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:38:46.371+0000] {processor.py:186} INFO - Started process (PID=6207) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:38:46.373+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:38:46.375+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:38:46.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:38:46.378+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:38:46.377+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:38:46.379+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:38:46.379+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:38:46.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:38:46.389+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:39:43.003+0000] {processor.py:186} INFO - Started process (PID=6263) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:39:43.005+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:39:43.008+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:39:43.008+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:39:43.011+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:39:43.010+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:39:43.011+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:39:43.011+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:39:43.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:39:43.023+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2025-01-28T06:40:38.956+0000] {processor.py:186} INFO - Started process (PID=6325) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:40:38.958+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:40:38.961+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:40:38.960+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:40:38.964+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:40:38.963+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:40:38.965+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:40:38.965+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:40:38.965+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:40:38.974+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:41:41.512+0000] {processor.py:186} INFO - Started process (PID=6503) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:41:41.514+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:41:41.516+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:41:41.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:41:41.520+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:41:41.519+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:41:41.520+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:41:41.520+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:41:41.521+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:41:41.531+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-01-28T06:42:39.796+0000] {processor.py:186} INFO - Started process (PID=6577) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:42:39.797+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:42:39.800+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:42:39.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:42:39.803+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:42:39.802+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:42:39.803+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:42:39.803+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:42:39.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:42:39.814+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-01-28T06:43:39.211+0000] {processor.py:186} INFO - Started process (PID=6633) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:43:39.213+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:43:39.215+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:43:39.215+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:43:39.218+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:43:39.218+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:43:39.218+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:43:39.218+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:43:39.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:43:39.229+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:44:47.307+0000] {processor.py:186} INFO - Started process (PID=6698) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:44:47.308+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:44:47.311+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:44:47.310+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:44:47.314+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:44:47.314+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:44:47.315+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:44:47.315+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:44:47.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:44:47.324+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:45:45.610+0000] {processor.py:186} INFO - Started process (PID=6834) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:45:45.611+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:45:45.613+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:45:45.613+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:45:45.617+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:45:45.616+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:45:45.617+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:45:45.617+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:45:45.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:45:45.627+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-01-28T06:46:36.175+0000] {processor.py:186} INFO - Started process (PID=6978) to work on /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:46:36.176+0000] {processor.py:914} INFO - Processing file /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T06:46:36.179+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:46:36.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:46:36.182+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:46:36.182+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T06:46:36.183+0000] {logging_mixin.py:190} INFO - [2025-01-28T06:46:36.182+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T06:46:36.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T06:46:36.194+0000] {processor.py:208} INFO - Processing /home/ubuntu/.local/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
